/**  
*    Class Name: AP01_TestDataTokens
*    Author: Rahul
*    Date: 20-November-2013
*    Description: This class is intended to declare all static variable for test classes
*    History
*    --------
**/
@isTest public class AP01_TestDataTokens{
    
    public static final string COMMUNITY_PORTAL_PROFILE = 'Community Portal';
    
    public static final string COMMUNITY_PORTAL_MANAGER_PROFILE = 'Community Portal Manager';
    
    public static final string SITE_LOGIN_USER_NAME = 'test@salesforce.com';
    
    public static final string SITE_LOGIN_PASSWORD = '123456789';
    
    public static final string BROKER_FIRM_HCC_ID ='545412';
    
    public static final string ACCOUNT_NAME='TEST ACCOUNT';
    
    public static final string PHONE='616-643-7555';
    
    public static final string TAX_ID ='0001';
    
    public static final string ACCOUNT_TIN_TYPE = 'Tax-ID';
    
    public static final string CONTACT_F_NAME = 'Test';
    
    public static final string CONTACT_L_NAME = 'Test';
    
    public static final string PORTAL_ACCOUNT_NAME= 'Test Portal Account';
    
    public static final string CONT_EMPLOYEE_ID = '1234'; 
    
    public static final string EMPLOYEE_AFFILIATE_FACILITY = 'Sutter Shared Services';
    
    public static final string MEMBER_ID_FIELD = '12345678';
    
    public static final string MEMBER_HCC_ID = '12345678';
    
    public static final string SUPPLIER_Tax_ID = '7676';
    
    public static final string SUPPLIER_NPI ='4343';
    
    public static final string PROVIDER_NPI = '111123';
    
    public static final string VENDOR_ID= '3131';
    
    public static final string VENDOR_TaxID= '090912';
    
    public static final string EMPLOYEE_UNION_AFFILIATE='CHEU';
    
    public static final string EMPLOYEE_EMPLOYMENT_STATUS = 'AB';
    
    public static final string EMPLOYEE_EEO_SUBCODE = '1';
    
    public static final string GURANTOR_NAME ='Guarantor';
    
    public static final string PATIENT_NAME ='Test_Patient';
    
    public static final string PATIENT_FIRST_NAME ='Test_Patient_FirstName';
    
    public static final string PATIENT_LAST_NAME ='Test_Patient_LastName';
    
    public static final string PATIENT_EPI_ID='123';
    
    public static final string PATIENT_DOTONE = 'def@@987'; 
    
    public static final string PATIENT_ACCOUNT_NUMBER = '1234';
    
    public static final string GURANTOR_ID_LOOKUP = '12344567';
    
    public static final string PATIENT_DOTONE_LOOKUP = '123445678';
    
    public static final string SHPCLAIMHDR_CLAIM_HCC_ID = 'C0001234-01';
    
    public static final string CLAIM_MEMBER_ID_FIELD = '123456';
    
    public static final string SHPCLAIMHDR_SUPPLIER_HCC_ID = 'S0001234-01';
    
    public static final string USER_FIRST_NAME ='test';
    
    public static final string USER_LAST_NAME ='user';
    
    public static final string USER_NAME ='TesUser1239123@acme.com';
    
    public static final string USER_NAME1 ='TesUser1240123@acme.com';
    
    public static final string USER_EMAIL ='TEST978@SUTTERHEALTH.COM';
    
    public static final string USER_EMAIL1 ='TEST1000@SUTTERHEALTH.COM';
    
    public static final string ALIAS ='tUSR';
    
    public static final string ALIAS1 ='tUSR1';
    
    public static final string TIME_ZONES_ID_KEY ='America/Los_Angeles';
    
    public static final string COMMUNITY_NICK_NAME ='nickname';
    
    public static final string EMAIL_ENCODING_KEYS = 'UTF-8';
    
    public static final string LANGUAGE_LOCALE_KEY= 'en_US';
    
    public static final string LOCALE_SID_KEY= 'en_US';
    
    public static final string OLD_PASSWORD= '123456';
    
    public static final string NEW_PASSWORD= 'qwerty1';
    
    public static final string START_URL= '/SH_Landing';//New Community Portal Redirecting Page
    
    public static final string FORWARD_TO_CUSTOM_START_PAGE= '/customLogin?startURL=';
    
    public static final string FIRST_NAME= 'FirstName';
    
    public static final string LAST_NAME= 'LastName';
    
    public static final string EMAIL= 'test@force.com';
    
    public static final string REGISTER_USER= '/apex/communitiesselfregconfirm';
    
    public static final string FORGOT_PASSWORD= '/apex/forgotpasswordconfirm';
    
    public static final string CONFIRM_PASSWORD= 'abcd123';
    
    public static final string PASSWORD= 'abcd1234';
    
    public static final string SITE_REGISTER_USER= '/apex/siteregisterconfirm';
    
    public static final string PORTAL_TYPE= 'None';
    
    public static final string S3_PROFILE_NAME= 'S3 Finance Accounting Agent';
    
    public static final string INTEGRATION_PROFILE_NAME= 'Integration';
    
    public static final string SHP_PROFILE_NAME= 'SHP Agent';
    
    public static final string SHP_SALES_PROFILE_NAME= 'SHP Sales';
    
    public static final string CONTACT_FIRST_NAME= 'Bob';
    
    public static final string CONTACT_LAST_NAME= 'Robert';
    
    public static final string CONTACT_PHONE= 'Phone';
    
    public static final string CONTACT_BIRTH_DATE= '11/11/2011';
    
    public static final string CONTACT_EMPLOYEE_UNION_AFFILIATE= 'CAN';
    
    public static final string CONTACT_EMPLOYEE_AFFILIATE_FACILITY= 'Adolescent Treatment Center';
    
    public static final string CONTACT_EMPLOYEE_EMPLOYMENT_STATUS= 'AA';
    
    public static final string CONTACT_EMPLOYEE_WORK_EMAIL= 'bobrobert@sutter.com';
    
    public static final string CONTACT_MAILING_STREET= '123 Place Dr.';
    
    public static final string CONTACT_MAILING_CITY= 'Roseville';
    
    public static final string CONTACT_MAILING_STATE= 'CA';
    
    public static final string CONTACT_MAILING_POSTAL_CODE= '95678';
    
    public static final string CONTACT_MEMBER_HCC_ID= 'M732873923-73';
    
    public static final string CONTACT_MEMBER_ID_FIELD= '73287392373';
    
    public static final string CONTACT_ACCOUNT= 'TestAccount';
    
    public static final string TEST_GUARANTOR= 'testGuarantor';
    
    public static final string TEST_PATIENT_NAME= 'testPatient';
    
    public static final string PATIENT_DOT_ONE= '827183723';
    
    public static final string TEST_PATIENT_ACCOUNT= '8112032093';
    
    public static final string CASE_ORIGIN= 'testOrigin';
    
    public static final string CASE_CONTACT_REGION= 'testRegion';
    
    public static final string CASE_GRIEVANCE_WEB_FORM_MEMBER_ID1= 'M732873923-73';
    
    public static final string CASE_GRIEVANCE_WEB_FORM_MEMBER_ID2= '73287392373';
    
    public static final string GRIEVANCE_RECORD_TYPE= 'Grievance Web Form Interaction Log';
    
    public static final string GROUP_SHP_ENROLLMENT= 'SHP Enrollment';
    
    public static final string GROUP_TIER1_HR_BENEFITS= '[Tier 1] HR Benefits';
    
    public static final string RECORD_TYPE_CV_ADDRESS_CHANGE_REQUEST= 'CV - Address Change Request';
    
    public static final string PORTAL_USER_NAME= 'brandon.k.cassis@testportaluser.com';
    
    public static final string CASE_NEW_STATUS= 'New';
    
    public static final string CASE_CLOSED_STATUS= 'Closed';
    
    public static final string CASE_CLOSED_REASON= 'Because';
    
    public static final string QUEUE= 'Queue';
    
    public static final string MEMBER= 'Member';
    
    public static final string CONTACT= 'Contact';
    
    public static final string S3_CASE= 'Case';
    
    
    public static final string RAND_FAX= '5551234';
    
    public static final string EXCEPTION_MSG= 'Util Execption';
    
    public static final string ERROR_MSG= 'Util Execption 1';
    
    public static final string EMAIL_ADDRESS= 'test@accenture.com';
    
    
    public static final string SET_REPLY_TO= 'developer@acme.com';
    
    public static final string SET_SENDER_DISPLAY_NAME= 'Apex error message';
    
    public static final string SET_SUBJECT= 'Error from Org, Exception Not Logged';
    
    public static final string MY_PROFILE_PAGE_CONTROLLER_MESSGE1= 'firstname should have been set as the firstname of the user for the contact';
    
    public static final string MY_PROFILE_PAGE_CONTROLLER_MESSGE2= 'lastname should have been set as the lastname of the user for the contact';
    
    public static final string MY_PROFILE_PAGE_CONTROLLER_MESSGE3= 'Did not successfully load the current user';
    
    public static final string MY_PROFILE_PAGE_CONTROLLER_MESSGE4= 'isEdit should default to false';
    
    public static final string USER_TYPE= 'CustomerSuccess';
    
    public static final string NONE= 'None';
    
    public static final string USER= 'User';
    
    public static final string GUEST= 'Guest';
    
    public static final string FALSE_FLAG= 'false';
    
    public static final string ANONYMOUS= 'Anonymous';
    
    public static final string ANONYMOUS_ANSWER= 'Test';
    
    public static final string RESULT_PAGE_URL= '/apex/ResultsPage?id=';
     
    public static final string VIEW_SURVEY_CHECK_REQUIRED= 'NO RESPONSE';
    
    
    
    public static final string SURVEY_THANK_YOU_TEXT= 'new stuff';
    
    public static final string SURVEY_THANK_YOU_URL= 'more new stff';
    
    public static final String CLAIM_SEARCH_PARAMETERS = 'memberId=123456&providerId=S0001234-01&caseStatus=false&custId=';
    
    public static final String CLAIM_SEARCH_PARAMETERS_FOR_PROVIDER = 'memberId=123456&providerId=S0001234-01&caseStatus=false&custId=';
    
    public static final String CLAIM_SEARCH_PAGE_REFERENCE = '/apex/VFP02_Claim_Search?';
    
    public static final String CLAIM_ID = 'C0001234-01';
    
    public static final String ENTITLEMENT = 'Test Ent';
    
    public static final String RECTYPE ='test';
    
    public static final String CONTACT_OWNER_MESSAGE ='You can only change to a User of SHP Sales Profile';
    
    public static final String REQUEST_RESPONSE_STUB ='20131202000017';
    
    public static final String CLAIM_DETAIL_REFERENCE ='/apex/VFP05_Claim_Detail?hccid=20131003000034';
    
    public static final String HCCID = '20131003000034';
    
    public static final String HCC_ID ='234562345';
    
    public static final String EMP_INQUIRY_RT_NAME = 'Employee Inquiry';
    
    public static final String ORIGIN = 'Phone';
    
    public static final String CASE_REASON = 'DMHC Additional Information';
    
    public static final String CASE_SECONDARY_REASON_NON_EXP = 'Exempt';
    
    public static final String CASE_SECONDARY_REASON_EXP = 'Expedited';
   
    public static final String ISSUE_DESCRIPTION = 'Access to Care - Distance';
    
    public static final String GRIEVANCE_REASON = 'Severe pain';
    
    public static final String GRIEVANCE_SR_RECORDTYPE = 'Grievance';
    
    public static final String ENTITLEMNT_NON_EXP = 'SHP Grievance Entitlement';
    
    public static final String ENTITLEMNT_EXP = 'SHP Grievance Entitlement for Expedited';
    
    public static final String CV_PORTAL_ADDRESS_CHANGE = '/apex/VFP16_CV_Portal?RT=CV_Address_Change_Request';
    
    public static final String CV_PORTAL_APPLICATION_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Application_Request';
    
    public static final String CV_PORTAL_DATA_CHANGE_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Data_Change_Request';
    
    public static final String CV_PORTAL_EXPIRABLES_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Expirables_Request';
    
    public static final String CV_PORTAL_OTHER_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Other_Request';
    
    public static final String CV_PORTAL_REAPPLICATION_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Reapplication_Request';
    
    public static final String CV_PORTAL_REPORT_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Report_Request';
    
    public static final String CV_PORTAL_RUSH_APPLICATION_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Rush_Application_Request';
    
    public static final String CV_PORTAL_TEMPORARY_PRIVILEGE_REQUEST = '/apex/VFP16_CV_Portal?RT=CV_Temporary_Privilege_Request';
    
    public static final String CV_PORTAL_PAGE = '/apex/VFP16_CV_Portal';
    
    public static final integer amount= 12345;
    
    public static final string sc_address = '222 folsom';
    
    public static final string mobilePhone = '(234) 987-8999';
    
    public static final string scAddressLine2 = '2nd ST';
    
    public static final string sc_city = 'test';
    
    public static final string sc_state = 'Tx';
    
    public static final string sc_securePhone = '(234) 987-8012';
    
    public static final string sc_secureFax = '(234) 987-8111';
    
    public static final string sc_zipCode = '45678';
    
    public static final string sc_Admin_Assistant = 'test1';
    
    public static final string sc_Admin_Assistant_Email = 'test1@email.com';
    
    public static final string sc_Admin_Assistant_Title = 'Dr';
    
    public static final string sc_Admin_Assistant_Phone = '(234) 987-8999';
    
    public static final string sc_Provider_Access_Type = 'No Access';
    
    public static final string ADDRESS_LINE1 = '1403 a street';
    public static final string ADDRESS_LINE2 = 'apt 129';
    public static final string CITY = 'sacramento';
    public static final string STATE = 'CA';
    public static final string ZIP_CODE = '99511';
    public static final string SECURE_PHONE = '(999) 123-9967';
    public static final string SECURE_FAX = '(999) 123-9967';
    public static final string SERIAL_NUMBER_0 = '0';
    public static final string SERIAL_NUMBER_1 = '1';
    public static final string SERIAL_NUMBER_2 = '2';
    public static final string SERIAL_NUMBER_3 = '3';
    public static final string ADDR3_ADDRESS_LINE1 = '1401 a street';
    public static final string ADDR3_SECURE_PHONE = '(999) 123-9997';
    public static final string ADDR3_SECURE_FAX = '(999) 123-9997';
    public static final string ADDR2_ADDRESS_LINE1 = '1400 a street';
    public static final string ADDR2_SECURE_PHONE = '(234) 456-3456';
    public static final string ADDR2_SECURE_FAX = '(234) 456-3456';
    
    public static final string NEG_ADDRESS_LINE1 = 'CareOf 123';
    public static final string NEG_SECURE_PHONE = '(234) 456';
    public static final string NEG_SECURE_FAX = '(234) 456';
    public static final string NEG_SECURE_PHONE_EXT = 'abcd';
    

}