/**
   @Author      : IDC Offshore
   @name        : ContactTriggerHelperClass
   @CreateDate  : 08/04/2015 (DD/MM/YYYY)
   @Description : REQ 3399 - Class for preventing execution of both Provider Creation and Updation method in ManageContactDatabase.
   @Version     : 1.0
   @reference   : NA
*/


public class ContactTriggerHelper {

/** Static variable initialized to true to allow execution and when its is false,it will prevent execution **/

public static boolean RUNCODE= true;


}