/**************************************************
 *     Class Name  : HighRoads_ArchivedContacts   *
 *     Author      : IDC-Offshore                 *
 *     Date        : 06-Oct-2016                  *
 *     Project Name: Sutter Health                *
 *     Description : Req-3880					  *
 * 					 Used for recursion protection*
 **************************************************/
public class HighRoads_ArchivedContacts {
	public static boolean isByPassValidationUpdated = true;
    public static boolean isContactBeforeInsert = true;
    public static boolean isContactBeforeUpdate = true;
    
}