/**********************************************************************
Class Name   : HighRoads_ConstantsTest
Date Created : 17-03-2017
Created By   : Deloitte
Description  : Test class to cover the HighRoads_Constants class
**********************************************************************/
@isTest
public class HighRoads_ConstantsTest {
     
     static testMethod void testData() {
        HighRoads_Constants con = new HighRoads_Constants();
     }
}