/*****************************************************
Class Name: PDIEAFFacilityTriggerHelper 
Created By: Nagarjuna Kaipu
Created Date: 10/10/2016
Description: used for trigger recursive variables
*****************************************************/
public class PDIEAFFacilityTriggerHelper {
    public static boolean firstRunFacilityBeforeUpdate = true;
    public static boolean firstRunFacilityBeforeInsert = true;
}